version: '3'

services:
  jekyll:
    image: jekyll/jekyll:4.0
    command: jekyll serve --watch --force_polling --verbose --baseurl '/'
    ports:
      - 4000:4000
    volumes:
      - ./docs:/srv/jekyll